options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Build the image for streamlit-app
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/<PROJECT-ID>/streamlit-app:latest', './streamlit-app']
    id: 'Build streamlit-app'

  # Push the image for streamlit-app
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/<PROJECT-ID>/streamlit-app:latest']
    id: 'Push streamlit-app'
    waitFor: ['Build streamlit-app']

  # Build the image for signin
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/<PROJECT-ID>/signin:latest', './nextjs-signin']
    id: 'Build signin'

  # Push the image for signin
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/<PROJECT-ID>/signin:latest']
    id: 'Push signin'
    waitFor: ['Build signin']

  # Deploy to Cloud Run for streamlit-app
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'streamlit-app', '--image', 'gcr.io/<PROJECT-ID>/streamlit-app:latest', '--platform', 'managed', '--region', 'us-central1']
    id: 'Deploy streamlit-app'
    waitFor: ['Push streamlit-app']

  # Deploy to Cloud Run for signin
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'signin', '--image', 'gcr.io/<PROJECT-ID>/signin:latest', '--platform', 'managed', '--region', 'us-central1']
    id: 'Deploy signin'
    waitFor: ['Push signin']

images:
  - 'gcr.io/<PROJECT-ID>/streamlit-app:latest'
  - 'gcr.io/<PROJECT-ID>/signin:latest'
